=== vruggiero/ICON/externals/art/runctrl_examples/xml_ctrl/DONOT_USE/coagulate.dtd
<!ELEMENT coagulate (smallmode+)>
<!ELEMENT smallmode (nmodes, bigmode+)>
<!ATTLIST smallmode
  id  ID  #REQUIRED
>
<!ELEMENT nmodes (#PCDATA)>
<!ATTLIST nmodes
  type CDATA #REQUIRED
>
<!ELEMENT bigmode (#PCDATA)>
<!ATTLIST bigmode
  id  CDATA  #REQUIRED
  type  CDATA #REQUIRED
>

=== vruggiero/ICON/run/xml_art/art_dustrad_R2B4N5/coagulate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
ICON

Copyright (C) 2004-2024, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
Contact information: icon-model.org
See AUTHORS.TXT for a list of authors
See LICENSES/ for license information
SPDX-License-Identifier: BSD-3-Clause
-->
<!DOCTYPE coagulate SYSTEM "coagulate.dtd">

<coagulate>
  <smallmode id="sol_ait">
    <nmodes type="int">9</nmodes>
    <bigmode id="sol_ait" type="char">sol_ait</bigmode>
    <bigmode id="insol_ait" type="char">mixed_ait</bigmode>
    <bigmode id="mixed_ait" type="char">mixed_ait</bigmode>
    <bigmode id="sol_acc" type="char">sol_acc</bigmode>
    <bigmode id="insol_acc" type="char">mixed_acc</bigmode>
    <bigmode id="mixed_acc" type="char">mixed_acc</bigmode>
    <bigmode id="sol_coa" type="char">sol_coa</bigmode>
    <bigmode id="insol_coa" type="char">mixed_coa</bigmode>
    <bigmode id="mixed_coa" type="char">mixed_coa</bigmode>
  </smallmode>
  <smallmode id="insol_ait">
    <nmodes type="int">8</nmodes>
    <bigmode id="insol_ait" type="char">insol_ait</bigmode>
    <bigmode id="mixed_ait" type="char">mixed_ait</bigmode>
    <bigmode id="sol_acc" type="char">mixed_acc</bigmode>
    <bigmode id="insol_acc" type="char">insol_acc</bigmode>
    <bigmode id="mixed_acc" type="char">mixed_acc</bigmode>
    <bigmode id="sol_coa" type="char">mixed_coa</bigmode>
    <bigmode id="insol_coa" type="char">insol_coa</bigmode>
    <bigmode id="mixed_coa" type="char">mixed_coa</bigmode>
  </smallmode>
  <smallmode id="mixed_ait">
    <nmodes type="int">7</nmodes>
    <bigmode id="mixed_ait" type="char">mixed_ait</bigmode>
    <bigmode id="sol_acc" type="char">mixed_acc</bigmode>
    <bigmode id="insol_acc" type="char">mixed_acc</bigmode>
    <bigmode id="mixed_acc" type="char">mixed_acc</bigmode>
    <bigmode id="sol_coa" type="char">mixed_coa</bigmode>
    <bigmode id="insol_coa" type="char">mixed_coa</bigmode>
    <bigmode id="mixed_coa" type="char">mixed_coa</bigmode>
  </smallmode>
  <smallmode id="sol_acc">
    <nmodes type="int">6</nmodes>
    <bigmode id="sol_acc" type="char">sol_acc</bigmode>
    <bigmode id="insol_acc" type="char">mixed_acc</bigmode>
    <bigmode id="mixed_acc" type="char">mixed_acc</bigmode>
    <bigmode id="sol_coa" type="char">sol_coa</bigmode>
    <bigmode id="insol_coa" type="char">mixed_coa</bigmode>
    <bigmode id="mixed_coa" type="char">mixed_coa</bigmode>
  </smallmode>
  <smallmode id="insol_acc">
    <nmodes type="int">5</nmodes>
    <bigmode id="insol_acc" type="char">insol_acc</bigmode>
    <bigmode id="mixed_acc" type="char">mixed_acc</bigmode>
    <bigmode id="sol_coa" type="char">mixed_coa</bigmode>
    <bigmode id="insol_coa" type="char">insol_coa</bigmode>
    <bigmode id="mixed_coa" type="char">mixed_coa</bigmode>
  </smallmode>
  <smallmode id="mixed_acc">
    <nmodes type="int">4</nmodes>
    <bigmode id="mixed_acc" type="char">mixed_acc</bigmode>
    <bigmode id="sol_coa" type="char">mixed_coa</bigmode>
    <bigmode id="insol_coa" type="char">mixed_coa</bigmode>
    <bigmode id="mixed_coa" type="char">mixed_coa</bigmode>
  </smallmode>
  <smallmode id="sol_coa">
    <nmodes type="int">3</nmodes>
    <bigmode id="sol_coa" type="char">sol_coa</bigmode>
    <bigmode id="insol_coa" type="char">mixed_coa</bigmode>
    <bigmode id="mixed_coa" type="char">mixed_coa</bigmode>
  </smallmode>
  <smallmode id="insol_coa">
    <nmodes type="int">2</nmodes>
    <bigmode id="insol_coa" type="char">insol_coa</bigmode>
    <bigmode id="mixed_coa" type="char">mixed_coa</bigmode>
  </smallmode>
  <smallmode id="mixed_coa">
    <nmodes type="int">1</nmodes>
    <bigmode id="mixed_coa" type="char">mixed_coa</bigmode>
  </smallmode>
</coagulate>

=== vruggiero/ICON/externals/art/runctrl_examples/xml_ctrl/DONOT_USE/coagulate_red.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE coagulate SYSTEM "coagulate.dtd">

<coagulate>
  <smallmode id="sol_ait">
    <nmodes type="int">3</nmodes>
    <bigmode id="sol_ait" type="char">sol_ait</bigmode>
    <bigmode id="sol_acc" type="char">sol_acc</bigmode>
    <bigmode id="sol_coa" type="char">sol_coa</bigmode>
  </smallmode>
  <smallmode id="sol_acc">
    <nmodes type="int">2</nmodes>
    <bigmode id="sol_acc" type="char">sol_acc</bigmode>
    <bigmode id="sol_coa" type="char">sol_coa</bigmode>
  </smallmode>
  <smallmode id="sol_coa">
    <nmodes type="int">1</nmodes>
    <bigmode id="sol_coa" type="char">sol_coa</bigmode>
  </smallmode>
</coagulate>

=== vruggiero/ICON/externals/art/runctrl_examples/xml_ctrl/DUST_RAD/coagulate_dustrad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE coagulate SYSTEM "coagulate.dtd">

<coagulate>
  <smallmode id="sol_acc">
    <nmodes type="int">6</nmodes>
    <bigmode id="sol_acc" type="char">sol_acc</bigmode>
    <bigmode id="insol_acc" type="char">mixed_acc</bigmode>
    <bigmode id="mixed_acc" type="char">mixed_acc</bigmode>
    <bigmode id="sol_coa" type="char">sol_coa</bigmode>
    <bigmode id="insol_coa" type="char">mixed_coa</bigmode>
    <bigmode id="mixed_coa" type="char">mixed_coa</bigmode>
  </smallmode>
  <smallmode id="insol_acc">
    <nmodes type="int">5</nmodes>
    <bigmode id="insol_acc" type="char">insol_acc</bigmode>
    <bigmode id="mixed_acc" type="char">mixed_acc</bigmode>
    <bigmode id="sol_coa" type="char">mixed_coa</bigmode>
    <bigmode id="insol_coa" type="char">insol_coa</bigmode>
    <bigmode id="mixed_coa" type="char">mixed_coa</bigmode>
  </smallmode>
  <smallmode id="mixed_acc">
    <nmodes type="int">4</nmodes>
    <bigmode id="mixed_acc" type="char">mixed_acc</bigmode>
    <bigmode id="sol_coa" type="char">mixed_coa</bigmode>
    <bigmode id="insol_coa" type="char">mixed_coa</bigmode>
    <bigmode id="mixed_coa" type="char">mixed_coa</bigmode>
  </smallmode>
  <smallmode id="sol_coa">
    <nmodes type="int">3</nmodes>
    <bigmode id="sol_coa" type="char">sol_coa</bigmode>
    <bigmode id="insol_coa" type="char">mixed_coa</bigmode>
    <bigmode id="mixed_coa" type="char">mixed_coa</bigmode>
  </smallmode>
  <smallmode id="insol_coa">
    <nmodes type="int">2</nmodes>
    <bigmode id="insol_coa" type="char">insol_coa</bigmode>
    <bigmode id="mixed_coa" type="char">mixed_coa</bigmode>
  </smallmode>
  <smallmode id="mixed_coa">
    <nmodes type="int">1</nmodes>
    <bigmode id="mixed_coa" type="char">mixed_coa</bigmode>
  </smallmode>
</coagulate>
