=== vruggiero/ICON/externals/art/runctrl_examples/xml_ctrl/DONOT_USE/Meng_ICON_CMD_USE.dtd
<!ELEMENT visparams (mode+)>
<!ATTLIST visparams
  dia_max_factor CDATA #REQUIRED
  dia_min_factor CDATA #REQUIRED
>
<!ELEMENT mode (waveband+)>
<!ATTLIST mode
  name    ID    #REQUIRED
  num_params CDATA #REQUIRED
>
<!ELEMENT waveband (ext, ssa, asy)>
<!ATTLIST waveband
  lambda_max CDATA #REQUIRED
  lambda_min CDATA #REQUIRED
  number    ID    #REQUIRED
>
<!ELEMENT ext EMPTY>
<!ATTLIST ext
  default_max CDATA #REQUIRED
  default_min CDATA #REQUIRED
  p1 CDATA #REQUIRED
  p2 CDATA #REQUIRED
  p3 CDATA #REQUIRED
  p4 CDATA #REQUIRED
>
<!ELEMENT ssa EMPTY>
<!ATTLIST ssa
  default_max CDATA #REQUIRED
  default_min CDATA #REQUIRED
  p1 CDATA #REQUIRED
  p2 CDATA #REQUIRED
  p3 CDATA #REQUIRED
  p4 CDATA #REQUIRED
>
<!ELEMENT asy EMPTY>
<!ATTLIST asy
  default_max CDATA #REQUIRED
  default_min CDATA #REQUIRED
  p1 CDATA #REQUIRED
  p2 CDATA #REQUIRED
  p3 CDATA #REQUIRED
  p4 CDATA #REQUIRED
>

=== vruggiero/ICON/externals/art/runctrl_examples/xml_ctrl/DUST_RAD/Meng_ICON_CMD_USE.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE visparams SYSTEM "Meng_ICON_CMD_USE.dtd">
<visparams dia_max_factor="1.25" dia_min_factor="0.25">
   <mode name="dusta" num_params="4">
      <waveband lambda_max="100000" lambda_min="28571.4286" number="1">
         <ext default_max="0.014889" default_min="0.004516" p1="9.9248e-11" p2="-1.9301e-07" p3="0.00012229" p4="-0.010153"/>
         <ssa default_max="0.001367" default_min="0.000062" p1="3.4376e-12" p2="-7.6756e-10" p3="2.7647e-07" p4="2.54e-05"/>
         <asy default_max="0.015495" default_min="0.00035471" p1="-3.3026e-12" p2="2.3403e-08" p3="-3.9178e-06" p4="0.00055949"/>
      </waveband>
      <waveband lambda_max="28571.4286" lambda_min="20000" number="2">
         <ext default_max="0.038001" default_min="0.035814" p1="3.0506e-11" p2="-3.9287e-08" p3="1.7383e-05" p4="0.033951"/>
         <ssa default_max="0.027343" default_min="0.000307" p1="3.1471e-11" p2="3.3974e-08" p3="-1.1088e-05" p4="0.0010974"/>
         <asy default_max="0.095430" default_min="0.002044" p1="-7.801e-11" p2="1.8930e-07" p3="-1.6624e-05" p4="0.0011109"/>
      </waveband>
      <waveband lambda_max="20000" lambda_min="15873.0159" number="3">
         <ext default_max="0.076087" default_min="0.075718" p1="-2.3213e-11" p2="5.4909e-08" p3="-3.314e-05" p4="0.079618"/>
         <ssa default_max="0.020599" default_min="0.000239" p1="8.62520e-12" p2="4.1806e-08" p3="-1.2231e-05" p4="0.0011025"/>
         <asy default_max="0.107980" default_min="0.003302" p1="-9.0296e-11" p2="2.0228e-07" p3="1.4047e-06" p4="-0.000641"/>
      </waveband>
      <waveband lambda_max="15873.0159" lambda_min="14285.7143" number="4">
         <ext default_max="0.112986" default_min="0.118498" p1="-6.3842e-11" p2="1.1802e-07" p3="-7.1096e-05" p4="0.12691"/>
         <ssa default_max="0.014305" default_min="0.000182" p1="1.31870e-13" p2="3.4546e-08" p3="-9.2947e-06" p4="0.00079541"/>
         <asy default_max="0.113330" default_min="0.004299" p1="-8.7586e-11" p2="1.9564e-07" p3="1.5952e-05" p4="-0.0018466"/>
      </waveband>
      <waveband lambda_max="14285.7143" lambda_min="12195.122" number="5">
         <ext default_max="0.086447" default_min="0.087898" p1="-5.0391e-11" p2="9.3335e-08" p3="-5.1593e-05" p4="0.093834"/>
         <ssa default_max="0.021152" default_min="0.000275" p1="-4.2451e-12" p2="5.5884e-08" p3="-1.492e-05" p4="0.0012659"/>
         <asy default_max="0.15063" default_min="0.0057932" p1="-1.2149e-10" p2="2.5786e-07" p3="2.5149e-05" p4="-0.0027749"/>
      </waveband>
      <waveband lambda_max="12195.122" lambda_min="10204.0816" number="6">
         <ext default_max="0.085735" default_min="0.060270" p1="-4.5917e-11" p2="1.2907e-07" p3="-4.4515e-05" p4="0.064245"/>
         <ssa default_max="0.195908" default_min="0.003360" p1="-5.2767e-10" p2="1.0441e-06" p3="-0.00026615" p4="0.021568"/>
         <asy default_max="0.24768" default_min="0.0099794" p1="-2.8376e-10" p2="4.3366e-07" p3="9.522e-05" p4="-0.010856"/>
      </waveband>
      <waveband lambda_max="10204.0816" lambda_min="9259.2593" number="7">
         <ext default_max="0.142034" default_min="0.098066" p1="-1.0833e-10" p2="2.364e-07" p3="-6.791e-05" p4="0.10333"/>
         <ssa default_max="0.169290" default_min="0.003191" p1="-4.7065e-10" p2="8.8357e-07" p3="-0.00020227" p4="0.015139"/>
         <asy default_max="0.25715" default_min="0.012991" p1="-2.2105e-10" p2="2.9373e-07" p3="0.00019447" p4="-0.01918"/>
      </waveband>
      <waveband lambda_max="9259.2593" lambda_min="8474.5763" number="8">
         <ext default_max="0.190430" default_min="0.195321" p1="-7.3666e-11" p2="1.146e-07" p3="-5.9643e-05" p4="0.20208"/>
         <ssa default_max="0.044197" default_min="0.000805" p1="-5.9283e-11" p2="1.6041e-07" p3="-3.4686e-05" p4="0.0025636"/>
         <asy default_max="0.2217" default_min="0.012146" p1="-1.6365e-10" p2="2.9067e-07" p3="0.0001142" p4="-0.010023"/>
      </waveband>
      <waveband lambda_max="8474.5763" lambda_min="7194.2446" number="9">
         <ext default_max="0.067629" default_min="0.061545" p1="-2.6811e-11" p2="5.188e-08" p3="-1.8421e-05" p4="0.063255"/>
         <ssa default_max="0.073423" default_min="0.001316" p1="-1.1277e-10" p2="2.8494e-07" p3="-6.4129e-05" p4="0.0048567"/>
         <asy default_max="0.30989" default_min="0.016378" p1="-2.5884e-10" p2="4.322e-07" p3="0.00015299" p4="-0.013652"/>
      </waveband>
      <waveband lambda_max="7194.2446" lambda_min="6756.7568" number="10">
         <ext default_max="0.168253" default_min="0.161676" p1="-5.6312e-11" p2="8.1213e-08" p3="-2.298e-05" p4="0.1635"/>
         <ssa default_max="0.075391" default_min="0.001642" p1="-1.3802e-10" p2="2.9885e-07" p3="-5.5672e-05" p4="0.0036361"/>
         <asy default_max="0.31808" default_min="0.019874" p1="-2.2627e-10" p2="3.4394e-07" p3="0.00022373" p4="-0.018678"/>
      </waveband>
      <waveband lambda_max="6756.7568" lambda_min="5555.5556" number="11">
         <ext default_max="0.095914" default_min="0.073770" p1="-5.1297e-11" p2="9.8576e-08" p3="-1.7619e-05" p4="0.074334"/>
         <ssa default_max="0.174884" default_min="0.004338" p1="-4.3095e-10" p2="7.7972e-07" p3="-0.00012816" p4="0.0071585"/>
         <asy default_max="0.40201" default_min="0.026373" p1="-3.0296e-10" p2="4.0034e-07" p3="0.00032755" p4="-0.027484"/>
      </waveband>
      <waveband lambda_max="5555.5556" lambda_min="4807.6923" number="12">
         <ext default_max="0.121382" default_min="0.087860" p1="-7.4363e-11" p2="1.3015e-07" p3="-1.1417e-05" p4="0.086798"/>
         <ssa default_max="0.218497" default_min="0.006891" p1="-5.5169e-10" p2="8.9492e-07" p3="-7.917e-05" p4="-0.00016201"/>
         <asy default_max="0.46312" default_min="0.035996" p1="-2.9197e-10" p2="2.9299e-07" p3="0.00049289" p4="-0.039044"/>
      </waveband>
      <waveband lambda_max="4807.6923" lambda_min="4444.4444" number="13">
         <ext default_max="0.229437" default_min="0.072239" p1="-3.9556e-10" p2="6.5986e-07" p3="-6.479e-05" p4="0.067989"/>
         <ssa default_max="0.534810" default_min="0.040558" p1="-5.0109e-10" p2="4.9559e-08" p3="0.0011246" p4="-0.13261"/>
         <asy default_max="0.51453" default_min="0.060826" p1="-9.5985e-11" p2="-2.4561e-07" p3="0.00092698" p4="-0.069999"/>
      </waveband>
      <waveband lambda_max="4444.4444" lambda_min="4201.6807" number="14">
         <ext default_max="0.259980" default_min="0.078433" p1="-4.6732e-10" p2="7.4291e-07" p3="-4.9288e-05" p4="0.070072"/>
         <ssa default_max="0.553207" default_min="0.048814" p1="-2.3501e-10" p2="-4.5908e-07" p3="0.0014157" p4="-0.15821"/>
         <asy default_max="0.53471" default_min="0.067989" p1="-1.7045e-11" p2="-4.1958e-07" p3="0.00105" p4="-0.077095"/>
      </waveband>
      <waveband lambda_max="4201.6807" lambda_min="3846.1538" number="15">
         <ext default_max="0.371052" default_min="0.083315" p1="-7.764e-10" p2="1.1595e-06" p3="-3.5002e-05" p4="0.063958"/>
         <ssa default_max="0.664012" default_min="0.097467" p1="1.1112e-09" p2="-2.9585e-06" p3="0.0028374" p4="-0.27471"/>
         <asy default_max="0.55771" default_min="0.092275" p1="1.7884e-10" p2="-8.4603e-07" p3="0.0013349" p4="-0.091983"/>
      </waveband>
      <waveband lambda_max="3846.1538" lambda_min="3076.9231" number="16">
         <ext default_max="0.482386" default_min="0.103644" p1="-1.0005e-09" p2="1.3032e-06" p3="0.00014489" p4="0.05388"/>
         <ssa default_max="0.689902" default_min="0.139228" p1="1.9076e-09" p2="-4.2867e-06" p3="0.0034538" p4="-0.29951"/>
         <asy default_max="0.59375" default_min="0.11554" p1="4.338e-10" p2="-1.3507e-06" p3="0.0016385" p4="-0.10285"/>
      </waveband>
      <waveband lambda_max="3846.1538" lambda_min="3076.9231" number="17">
         <ext default_max="0.482386" default_min="0.103644" p1="-1.0005e-09" p2="1.3032e-06" p3="0.00014489" p4="0.05388"/>
         <ssa default_max="0.689902" default_min="0.139228" p1="1.9076e-09" p2="-4.2867e-06" p3="0.0034538" p4="-0.29951"/>
         <asy default_max="0.59375" default_min="0.11554" p1="4.338e-10" p2="-1.3507e-06" p3="0.0016385" p4="-0.10285"/>
      </waveband>
      <waveband lambda_max="3076.9231" lambda_min="2500" number="18">
         <ext default_max="0.582833" default_min="0.043247" p1="-1.4502e-09" p2="1.7382e-06" p3="0.00033465" p4="-0.044559"/>
         <ssa default_max="0.950864" default_min="0.676499" p1="3.1997e-09" p2="-5.8427e-06" p3="0.0034931" p4="0.26401"/>
         <asy default_max="0.61935" default_min="0.15435" p1="9.606e-10" p2="-2.3327e-06" p3="0.0021484" p4="-0.11746"/>
      </waveband>
      <waveband lambda_max="2500" lambda_min="2150.5376" number="19">
         <ext default_max="0.743636" default_min="0.062094" p1="-1.4826e-09" p2="1.2119e-06" p3="0.0010764" p4="-0.12771"/>
         <ssa default_max="0.981064" default_min="0.886148" p1="1.2311e-09" p2="-2.2226e-06" p3="0.0013032" p4="0.73314"/>
         <asy default_max="0.63808" default_min="0.19353" p1="1.3205e-09" p2="-2.966e-06" p3="0.0024442" p4="-0.10674"/>
      </waveband>
      <waveband lambda_max="2150.5376" lambda_min="1941.7476" number="20">
         <ext default_max="0.880332" default_min="0.094703" p1="-1.1058e-09" p2="1.9543e-08" p3="0.0020716" p4="-0.22191"/>
         <ssa default_max="0.981875" default_min="0.910779" p1="9.329e-10" p2="-1.686e-06" p3="0.00098783" p4="0.79483"/>
         <asy default_max="0.65051" default_min="0.2254" p1="1.5549e-09" p2="-3.3499e-06" p3="0.0025985" p4="-0.087861"/>
      </waveband>
      <waveband lambda_max="1941.7476" lambda_min="1626.0163" number="21">
         <ext default_max="1.025505" default_min="0.147913" p1="-1.0342e-10" p2="-2.3156e-06" p3="0.0036438" p4="-0.35977"/>
         <ssa default_max="0.982308" default_min="0.930846" p1="6.8724e-10" p2="-1.2451e-06" p3="0.00072908" p4="0.84529"/>
         <asy default_max="0.66052" default_min="0.26229" p1="1.7542e-09" p2="-3.6595e-06" p3="0.0026979" p4="-0.057131"/>
      </waveband>
