=== vruggiero/ICON/externals/art/runctrl_examples/xml_ctrl/DONOT_USE/modes.dtd
<!ELEMENT modes (aerosol+,radio+,volcanic+)>
<!ELEMENT aerosol (d_gn, d_gm, sigma_g, rho)>
<!ATTLIST aerosol
  id  ID  #REQUIRED
  of  CDATA #REQUIRED
  type CDATA  #REQUIRED
>
<!ELEMENT d_gn (#PCDATA)>
<!ELEMENT d_gm (#PCDATA)>
<!ELEMENT sigma_g (#PCDATA)>
<!ELEMENT rho (#PCDATA)>
<!ELEMENT radio (imis, halflife)>
<!ATTLIST radio
  id  ID  #REQUIRED
  type  CDATA #REQUIRED
>
<!ELEMENT imis (#PCDATA)>
<!ELEMENT halflife (#PCDATA)>
<!ELEMENT volcanic (diam, rho)>
<!ATTLIST volcanic
  id  ID  #REQUIRED
  type  CDATA #REQUIRED
>
<!ELEMENT diam (#PCDATA)>
<!ELEMENT rho (#PCDATA)>

=== vruggiero/ICON/externals/art/runctrl_examples/xml_ctrl/DONOT_USE/modes_iart_seasalt2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modes SYSTEM "modes.dtd">

<modes>
  <aerosol id="seasa" of="seasalt" type="2mom">
    <kind type="char">2mom</kind>
    <d_gn type="real">0.100E-6</d_gn>
    <d_gm type="real">0.433E-6</d_gm>
    <sigma_g type="real">1.900E+0</sigma_g>
    <rho type="real">2.200E+3</rho>
  </aerosol>
  <aerosol id="seasb" of="seasalt" type="2mom">
    <kind type="char">2mom</kind>
    <d_gn type="real">3.000E-6</d_gn>
    <d_gm type="real">1.268E-5</d_gm>
    <sigma_g type="real">2.000E+0</sigma_g>
    <rho type="real">2.200E+3</rho>
  </aerosol>
  <aerosol id="seasc" of="seasalt" type="2mom">
    <kind type="char">2mom</kind>
    <d_gn type="real">3.000E-5</d_gn>
    <d_gm type="real">6.982E-5</d_gm>
    <sigma_g type="real">1.700E+0</sigma_g>
    <rho type="real">2.200E+3</rho>
  </aerosol>
</modes>
